### ISSUE TITLE
Use React as peer dependency

### ISSUE THREAD

**Issue by LucasBrandt** [googlemaps/react-wrapper#140]
Hi, thanks for building this package! It's exactly what I'm looking for.

When I use the `Wrapper` component in my application, I get the following error when it is rendered:

```
Uncaught Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.
```

I did some searching and found that a common cause for this problem is when there are two separate versions of React in use in your application. I checked in my project's `yarn.lock` and after installing this package, there's a new entry there for React, because my application depends on an older version of React than this package does:

```
react@16.8.6, react@^16.8.3:
  version "16.8.6"
  resolved "https://registry.yarnpkg.com/react/-/react-16.8.6.tgz#ad6c3a9614fd3a4e9ef51117f54d888da01f2bbe"
  integrity sha512-pC0uMkhLaHm11ZSJULfOBqV4tIZkx87ZLvbbQYunNixAAvjnC+snJCg0XQXn9VIsttVsbZP/H/ewzgsd5fxKXw==
  dependencies:
    loose-envify "^1.1.0"
    object-assign "^4.1.1"
    prop-types "^15.6.2"
    scheduler "^0.13.6"

-- New entry
react@^17.0.1:
  version "17.0.2"
  resolved "https://registry.yarnpkg.com/react/-/react-17.0.2.tgz#d0b5cc516d29eb3eee383f75b62864cfb6800037"
  integrity sha512-gnhPt75i/dq/z3/6q/0asP78D0u592D5L1pd7M8P+dck6Fu/jJeL6iVVK23fptSUZj8Vjf++7wXA8UNclGQcbA==
  dependencies:
    loose-envify "^1.1.0"
    object-assign "^4.1.1"
```

After taking a look at the `package.json` [here](https://github.com/googlemaps/react-wrapper/blob/main/package.json#L68), I see that React is in `dependencies`. I did some more reading and I found [some recommendations](https://stackoverflow.com/questions/43635703/what-should-be-peer-dependencies-when-creating-libs-in-webpack) that React should be set as a peer dependency.

I think this change alone wouldn't make it possible to use this package in my application as it stands, because we aren't on React 17 yet. If, through peer dependencies, this package also supported react 16.8 and above, I could use it! But that's another topic, and not a bug per se.

I haven't taken the time to create a sample app to reproduce this issue, but it should be reproducible by using this library in any application that has a different version of React as a regular dependency.

Let me know if any other details would be helpful! Thank you.

**Comment by LucasBrandt** [comment]
@jpoehnelt Thank you so much! I moved forward temporarily by mimicking this library in a component of my own, but as soon as I finish my current work I'll give this a shot again and follow up.

**Comment by LucasBrandt** [comment]
Hi @jpoehnelt following up as requested -  1.1.1 works perfectly! Thanks again for addressing this and changing the minimum version.

**Comment by jpoehnelt** [comment]
@LucasBrandt Can you share why you chose this library instead of one of the react component libraries? Thanks!

**Comment by LucasBrandt** [comment]
@jpoehnelt Sure - My project was previously using [`fullstackreact/google-maps-react`](https://github.com/fullstackreact/google-maps-react), which had been giving us no problems. 

The project uses [`react-geosuggest`](https://github.com/ubilabs/react-geosuggest) to allow selecting a location from the Google Places API throughout the application. There was a lot of code duplication doing that, so I wanted to create a reusable component to centralize some Geosuggest-related handling and styling. The library I was using previously didn't work for this use case because it has an [unresolved issue](https://github.com/fullstackreact/google-maps-react/issues/227) that when used to wrap a component, it would wrap it in an unstyleable div. That became an issue for my use case because the reusable component would need to be styleable, so I had to find something new.

I was looking for a simple library with the ability to delay rendering a component until the Google Maps JS library has been loaded. I was hoping to find something that makes it easy to render a placeholder in loading and error states, had good docs, and which seemed active in case there were issues to resolve later down the line. I didn't find many options, but this one seemed to fit the bill and you knocked it out of the park in terms of support for the issue!

**Comment by jpoehnelt** [comment]
Thanks for the response!
