### ISSUE TITLE
Basic demo link broken

### ISSUE THREAD

**Issue by rollie42** [googlemaps/react-wrapper#274]
Simply, the 'basic demo' as linked from the readme goes to 404 

Link: https://googlemaps.github.io/react-wrapper/public/basic/

**Comment by shuuji3** [comment]
I found the same issue. The above link is here: https://github.com/googlemaps/react-wrapper/blob/main/README.md?plain=1#L94

I also found another demo on the official Google Maps Documentation: [Adding a Map and Markers to a React Application  |  Maps JavaScript API](https://developers.google.com/maps/documentation/javascript/react-map). Maybe this can be used for the replacement.

**Comment by jpoehnelt** [comment]
Yeah, can use the demo on developers.google.com. I think this regression happened due to a change in build with rollup libraries. I'll take a look.

**Comment by shuuji3** [comment]
I can see the demo link was fixed. Thank you! 🙂
