### ISSUE TITLE
Adding places with examples

### ISSUE THREAD

**Issue by michaeljc827** [googlemaps/react-wrapper#292]
Could we have the ability to use places library with this wrapper? Specifically, an option to load the places API within the Maps script on load. Autocomplete would be a great feature to have.

**Comment by reneloperena** [comment]
This library uses `@googlemaps/js-api-loader`, so you can simply pass in `libraries` to your Wrapper component and load the places API. Ex:
```
  <Wrapper apiKey={...} libraries={['places']}>
    {....}
  </Wrapper>
```

**Comment by cvinuale** [comment]
> This library uses `@googlemaps/js-api-loader`, so you can simply pass in `libraries` to your Wrapper component and load the places API. Ex:
> 
> ```
>   <Wrapper apiKey={...} libraries={['places']}>
>     {....}
>   </Wrapper>
> ```

Thank you so much, you made my day!
