### ISSUE TITLE
Clustering

### ISSUE THREAD

**Issue by esharmony** [googlemaps/react-wrapper#314]
I'm not sure if it's possible, or if there is already simple solution to having clusters with this Library?
If not, it would be a great feature to have.

**Comment by jpoehnelt** [comment]
Clustering is out of scope for this library which is only focused on loading the Google Maps JS API.

**Comment by esharmony** [comment]
OK, thanks, I have followed some of the code design ideas used in this library and just used the standard API. Glad to know I am not missing anything.
