### ISSUE TITLE
Missing google namespace type definitions

### ISSUE THREAD

**Issue by lukasjengo** [googlemaps/react-wrapper#322]
Hey,

I experimented with using @googlemaps/react-wrapper library in my TypeScript Next.js project and ran into a type definition problem when following this repo installation guide. 

Managed to solve the problem and thought that it would be useful to add additional TypeScript support steps to this repo's README, so that other community members don't run into the same problem.

#### Steps to reproduce

1.  Install @googlemaps/react-wrapper library in Next.js TypeScript project.

#### Code example

![Capture](https://user-images.githubusercontent.com/38685058/151328406-1e690af7-5410-4790-b270-4f02ea8623d6.PNG)

#### Steps to fix

1.  Install @types/google.maps type definitions.

**Comment by jpoehnelt** [comment]
@lukasjengo Thank you for opening this issue. 🙏
Please check out these other resources that might be applicable:

- [Support Console](https://cloud.google.com/support/) - If you have a support contract.
- [Discord](https://discord.gg/9UpV862xZ9) - chat with other developers
- [StackOverflow](http://stackoverflow.com/questions/tagged/google-maps) - use the `google-maps` tag
- [Google Maps Platform issue trackers](https://developers.google.com/maps/support/#issue_tracker)
