### ISSUE TITLE
WrapperProps apiKey | Ubuntu 20 | Pkg 1.1.35

### ISSUE THREAD

**Issue by Rafcin** [googlemaps/react-wrapper#494]
#### Issue
Hello! So I'm trying to better strengthen my code by using better eslint configs and optimal tsconfigs, and while I was working on a project, I found an issue I had never encountered with <Wrapper> it seems that `apiKey` isn't an available prop. I looked at the interface, and it extends the JS loader package, so it should be fine however, I keep getting complaints it's not. I'm wondering could this be due to my tsconfig?

#### Code example

```
<Wrapper
   apiKey={String(
       process.env.NEXT_PUBLIC_GMAPS_DEV_API
   )}
   render={MapLoading}
>
```

#### Stack trace
```
Type '{ children: Element; apiKey: string; render: FC<any>; }' is not assignable to type 'IntrinsicAttributes & WrapperProps'.
  Property 'apiKey' does not exist on type 'IntrinsicAttributes & WrapperProps'.
```

**Comment by amuramoto** [comment]
I think you may be running into this:

https://stackoverflow.com/questions/59969756/not-assignable-to-type-intrinsicattributes-intrinsicclassattributes-react-js
