### ISSUE TITLE
Could not render map: CodeSandbox works fine but having issue in the localhost

### ISSUE THREAD

**Issue by Pourush1** [googlemaps/react-wrapper#502]
### Code used in the project
```
function MyMapComponent({ center, zoom }) {
  const ref = useRef(null);
  const [map, setMap] = useState();

  useEffect(() => {
    console.log("this got called", ref.current);
    if (ref.current && !map) {
      setMap(
        new window.google.maps.Map(ref.current, {
          center,
          zoom
        })
      );
    }
  }, [ref, map, center, zoom]);

  return <div ref={ref} style={{ flexGrow: "1", height: "100%" }} />;
}

const render = (status) => {
  if (status === "LOADING") {
    console.log("Loading...");
    return <h3>{status} ..</h3>;
  }
  if (status === "FAILURE") {
    console.log("Failing...");
    return <h3>{status} ...</h3>;
  }
  if (status === "SUCCESS") {
    console.log("Suceding...");
    return <h3>Success</h3>;
  }
  return null;
};

export default function App() {
  const center = { lat: -25.363, lng: 131.044 };
  const zoom = 4;
  return (
    <div style={{ display: 'flex', height: '100vh', width: '100vw' }}>
      <Wrapper apiKey="MY_KEY" render={render}>
        <MyMapComponent center={center} zoom={zoom} />
      </Wrapper>
    </div>
  );
}
```
This code works perfectly fine in the code sandbox but when I try to render it in my localhost it does not work. I got the empty screen first without passing the render prop, then I looked at the code of the library and passed the render prop. When I passed the render prop the status that I am getting is loading and accordingly, the Loading... status gets rendered on the page(image below). I can see in the library code, that in order to render the children component passed, it should have the status Success.

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/25923806/182050975-6a55fa53-5f9d-4250-b2db-35b5eae2d4d5.png">

 I am just copying and pasting the same code from the code sandbox where it is working. In my localhost, it seems the useEffect does not get called at all and does not instantiate the map. 

How can I solve this? I have tried a lot of things but with no success. 

Note: We are using SSR in the codebase. I thought this might be the issue and tried to render the App component once it gets mounted, but it did not work as well.  Any idea would be really helpful. 
Also, whenever I make a request to Google Maps API from the code sandbox I can see the request being made but not from my localhost. Here is the screenshot of that: 
<img width="1094" alt="image" src="https://user-images.githubusercontent.com/25923806/182051562-d37b3df5-cec2-4a78-89c9-a7a584b151db.png">

**Comment by amuramoto** [comment]
Are you seeing any errors in the console?

**Comment by Pourush1** [comment]
> Are you seeing any errors in the console?

No, I did not. Btw, I have solved this problem. It was not because of the maps, it was because of some webpack configuration that I missed. Thanks for the reply.

**Comment by VMBindraban** [comment]
> > Are you seeing any errors in the console?
> 
> No, I did not. Btw, I have solved this problem. It was not because of the maps, it was because of some webpack configuration that I missed. Thanks for the reply.

What webpack configuration did you miss?

**Comment by Pourush1** [comment]
> > > Are you seeing any errors in the console?
> > 
> > 
> > No, I did not. Btw, I have solved this problem. It was not because of the maps, it was because of some webpack configuration that I missed. Thanks for the reply.
> 
> What webpack configuration did you miss?

I was missing to include the hydrated frontend file, in the entry configuration of client-side scripts in webpack configuration.
``` entry : { product : ['.src/client/ProductFrontEnd.jsx']} ``` something like this and this file was hydrating the SSR rendered ccontent.
