### ISSUE TITLE
react-map sample problem in fresh react project

### ISSUE THREAD

**Issue by ebadta81** [googlemaps/react-wrapper#538]
Hello,

I am trying to use the react-map sample code in a new typescript react project, but I have errors  in the code.

It works in the js-samples project, so this is a configuration issue, but I cannot figure out the problem.

Please help me.

How to reproduce:

- npx create-react-app test --template typescript
- I copied the react-map/index.tsx file to my project root directory
- npm i --save @googlemaps/react-wrapper fast-equals @googlemaps/typescript-guards
- npm i -D @types/google.maps

I have these errors:
```
webpack compiled with 1 warning
ERROR in src/index.tsx:178:46
TS2769: No overload matches this call.
  The last overload gave the following error.
    Argument of type '{ map: google.maps.Map | undefined; }' is not assignable to parameter of type 'Partial<unknown> & Attributes'.
      Object literal may only specify known properties, and 'map' does not exist in type 'Partial<unknown> & Attributes'.
    176 |         if (React.isValidElement(child)) {
    177 |           // set the map prop on the child component
  > 178 |           return React.cloneElement(child, { map });
        |                                              ^^^
    179 |         }
    180 |       })}
    181 |     </>

ERROR in src/index.tsx:214:18
TS2560: Value of type '(a: any, b: any) => any' has no properties in common with type 'Partial<CreateComparatorCreatorOptions<undefined>>'. Did you mean to call it?
    212 |
    213 | const deepCompareEqualsForMaps = createCustomEqual(
  > 214 |   (deepEqual) => (a: any, b: any) => {
        |                  ^^^^^^^^^^^^^^^^^^^^^
    215 |     if (
    216 |       isLatLngLiteral(a) ||
    217 |       a instanceof google.maps.LatLng ||

ERROR in src/index.tsx:227:12
TS2349: This expression is not callable.
  Type 'CreateComparatorCreatorOptions<undefined>' has no call signatures.
    225 |
    226 |     // use fast-equals for other objects
  > 227 |     return deepEqual(a, b);
        |            ^^^^^^^^^
    228 |   }
    229 | );
    230 |

```

**Comment by denexapp** [comment]
How to fix this, 2 steps:

1. Downgrade `fast-equals` to version 3, `npm install fast-equals@^3.0.3`
2. Replace children prop type to `React.ReactElement<google.maps.MarkerOptions>[] | React.ReactElement<google.maps.MarkerOptions>` (credits to [this answer](https://stackoverflow.com/questions/73545744/google-maps-react-no-overload-matches-this-call/73564091))

So yeah, google's example is outdated
