### ISSUE TITLE
Map not displayed

### ISSUE THREAD

**Issue by fvilers** [googlemaps/react-wrapper#542]
#### Environment details

1. API: Maps
2. Windows 10 latest, Node 16.13.2
3. Brave 1.44.101 Chromium 106 / Edge 105 / Chrome 106
4. React 18.2 strict mode, Create React App 5.0.1, TypeScript 4.4.2

#### Steps to reproduce

  1. Create a new react app using the create-react-app package
  2. Add the @googlemaps/react-wrapper library
  3. Create a GoogleMap component following code sample at https://developers.google.com/maps/documentation/javascript/react-map and add it to the App (inside the Wrapper + API key)
  5. No error at build time, nor in the console, the map is not displayed but a request the the Google API is successfully made

![image](https://user-images.githubusercontent.com/1009621/193208208-aba45f77-b573-424d-8849-b61fa16a4492.png)

#### Code example

Full reproduction app is available at https://github.com/fvilers/googlemaps-react-wrapper-issue

**Comment by jbc2313** [comment]
Im having this same bug. any known fix yet?

**Comment by fvilers** [comment]
Seems like the fix is as simple as specifying a size to the map. See fix here: https://github.com/fvilers/googlemaps-react-wrapper-issue/tree/how-to-fix

**Comment by jbc2313** [comment]
Thank you, I did the same thing, I specified the size of the div containing the map, and not the map itself.

**Comment by efost** [comment]
Cheers @fvilers -- I've been trying to solve this for hours now and adding width and height to the map container did the trick!
