### ISSUE TITLE
Maps shows "Sorry, we have no imagery here" on iOS13

### ISSUE THREAD

**Issue by pupuza** [googlemaps/react-wrapper#830]
When running on an iPhone SE with iOS 13, Maps briefly displays images for about 1 second and then shows the error: "Sorry, we have no imagery here". It happens on all places, and on all zoom levels. However, this issue does not occur on devices running iOS 14 or later. 

- Device: iPhone SE
- OS: iOS 13
- Browser: Safari
- @googlemaps/react-wrapper version: 1.1.35
- Nextjs13
- Set zoom: 14
- Location: current location 
 
The API key is valid and enabled for Maps JavaScript API.
The issue occurs on a stable internet connection and over HTTPS.
Add full Policy

Please help resolve this issue. Thank you!

**Comment by usefulthink** [comment]
This is something completely unrelated to the react-wrapper, or at least, there's nothing we can do about that here.

It sounds a lot like an issue with Safari- and/or iOS-support (even the latest iOS13 Version was released almost 4 years ago and I remember the Safari version back then was missing a lot of features). There's already an issue about this in the [Google Maps Platform Issue Tracker](https://issuetracker.google.com/issues/348270704), which is the best place to discuss this.

**Comment by pupuza** [comment]
@usefulthink 

Thank you for your prompt response. However, I'm encountering an issue in another project where I'm using Next.js 14 and @googlemaps/react-wrapper version 1.1.35. Specifically, when I include the version parameter (&v=) in the apiKey, I encounter the following error:

"Oops! Something went wrong. This page didn't load Google Maps correctly. See the JavaScript console for technical details."

Upon investigation, I've identified that the &v= parameter is being encoded as %26v%3D, which appears to be causing the issue. Here's an example of the script generated on the website:


`<script id="__googleMapsScriptId" src="https://maps.googleapis.com/maps/api/js?libraries=core&amp;key=API_KEY%26v%3Dquarterly&amp;callback=google.maps.__ib__"></script>`

Interestingly, when I manually add the script without using the library, the &v= parameter is not incorrectly encoded, and the maps function normally. Could you please assist me in checking if there's a solution to resolve this encoding issue?

Your assistance in resolving this matter would be greatly appreciated.

Best regards,
