### ISSUE TITLE
Link to @visgl/react-google-maps from README

### ISSUE THREAD

**Issue by wangela** [googlemaps/react-wrapper#832]
Now that https://goo.gle/react-google-maps is [stable](https://mapsplatform.google.com/resources/blog/google-maps-platform-graduates-react-integration-library-to-1-0/), people who end up here may be interested in the full React support offered by that library beyond the loading wrapper that this library offers.

Let's add a link to the React Google Maps Library (both the homepage and the npm page) from the README of this library.

**Comment by jalvaradoas39** [comment]
I'd love to take this on! If it's okay with you, @wangela, I'd be happy to add the links to the README. Let me know if I should proceed, and I'll get started.
